import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { TanStackProvider } from "@/components/provider/tanstack-provider";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-Poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable}  antialiased`}
      >
        <TanStackProvider>
          {children}
        </TanStackProvider>
      </body>
    </html>
  );
}
